import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import ItemList from "./src/component/itemList";

export default function Home() {
  const [list, setList] = useState([]);
  const API_URL =
    "http://makeup-api.herokuapp.com/api/v1/products.json?product_type=lipstick";

  function getData() {
    axios.get(API_URL).then((res) => {
      setList(res.data);
    });
  }

  useEffect(() => {
    getData();
    console.log("UseEffect");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>베스트 상품</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <br></br>
        <div>베스트상품</div>
        <br></br>
      </main>
      <ItemList list={list}></ItemList>
      <footer className={styles.footer}>Powered by Azerc</footer>
    </div>
  );
}
